using UnityEngine;

namespace Shredsquatch.Core
{
    /// <summary>
    /// Automatically sets up missing references and creates required components at runtime.
    /// Attach this to a GameObject in your scene to ensure the game can run with minimal setup.
    /// </summary>
    [DefaultExecutionOrder(-1000)]
    public class AutoSetup : MonoBehaviour
    {
        [Header("Auto-Create Missing Systems")]
        [SerializeField] private bool _createGameManager = true;
        [SerializeField] private bool _createErrorRecovery = true;
        [SerializeField] private bool _findPlayerAutomatically = true;
        [SerializeField] private bool _createGroundIfMissing = true;
        
        [Header("Debug")]
        [SerializeField] private bool _logSetupActions = true;

        private void Awake()
        {
            SetupCoreSystems();
        }

        private void SetupCoreSystems()
        {
            // Ensure ErrorRecoveryManager exists first
            if (_createErrorRecovery && ErrorRecoveryManager.Instance == null)
            {
                var errObj = new GameObject("ErrorRecoveryManager");
                errObj.AddComponent<ErrorRecoveryManager>();
                DontDestroyOnLoad(errObj);
                Log("Created ErrorRecoveryManager");
            }

            // Ensure GameManager exists
            if (_createGameManager && GameManager.Instance == null)
            {
                var gmObj = new GameObject("GameManager");
                var gm = gmObj.AddComponent<GameManager>();
                DontDestroyOnLoad(gmObj);
                Log("Created GameManager");
            }

            // Find player and set reference
            if (_findPlayerAutomatically && GameManager.Instance != null)
            {
                var player = GameObject.FindGameObjectWithTag("Player");
                if (player != null)
                {
                    GameManager.Instance.SetPlayerReference(player.transform);
                    Log($"Found and set player reference: {player.name}");
                    
                    // Ensure player has required components
                    EnsurePlayerComponents(player);
                }
                else
                {
                    Log("Warning: No GameObject with 'Player' tag found");
                }
            }

            // Create ground if nothing exists
            if (_createGroundIfMissing)
            {
                var grounds = Physics.OverlapSphere(Vector3.zero, 1000f, LayerMask.GetMask("Ground", "Default"));
                if (grounds.Length == 0)
                {
                    CreateTestGround();
                }
            }
        }

        private void EnsurePlayerComponents(GameObject player)
        {
            // Ensure CharacterController exists
            if (player.GetComponent<CharacterController>() == null)
            {
                var cc = player.AddComponent<CharacterController>();
                cc.height = 1.8f;
                cc.radius = 0.5f;
                cc.center = new Vector3(0, 0.9f, 0);
                Log("Added CharacterController to player");
            }

            // Ensure PlayerInput exists
            if (player.GetComponent<Player.PlayerInput>() == null)
            {
                player.AddComponent<Player.PlayerInput>();
                Log("Added PlayerInput to player");
            }

            // Ensure SnowboardPhysics exists
            if (player.GetComponent<Player.SnowboardPhysics>() == null)
            {
                player.AddComponent<Player.SnowboardPhysics>();
                Log("Added SnowboardPhysics to player");
            }

            // Ensure PlayerController exists
            if (player.GetComponent<Player.PlayerController>() == null)
            {
                player.AddComponent<Player.PlayerController>();
                Log("Added PlayerController to player");
            }
        }

        private void CreateTestGround()
        {
            var ground = GameObject.CreatePrimitive(PrimitiveType.Plane);
            ground.name = "AutoGeneratedGround";
            ground.transform.localScale = new Vector3(100, 1, 200);
            ground.transform.position = new Vector3(0, 0, 100);
            ground.transform.rotation = Quaternion.Euler(5, 0, 0); // Slight downhill slope
            
            // Set layer
            int groundLayer = LayerMask.NameToLayer("Ground");
            if (groundLayer == -1) groundLayer = 0;
            ground.layer = groundLayer;
            
            // Make it white/snow colored
            var renderer = ground.GetComponent<Renderer>();
            if (renderer != null)
            {
                renderer.material.color = new Color(0.95f, 0.97f, 1f);
            }
            
            Log("Created test ground plane");
        }

        private void Log(string message)
        {
            if (_logSetupActions)
            {
                Debug.Log($"[AutoSetup] {message}");
            }
        }

        /// <summary>
        /// Call this to reset and re-run setup (useful for scene reloads)
        /// </summary>
        public void RerunSetup()
        {
            SetupCoreSystems();
        }
    }
}
